apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${APP_NAME}-gateway
  namespace: ${NAMESPACE}
spec:
  gatewayClassName: aws-alb
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: ${APP_NAME}-lbconfig
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: ${APP_FQDN}
    allowedRoutes:
      namespaces:
        from: Same
